# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'KooKoo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod "SwiftLocation"
  pod "Alamofire"
  pod "ZAlertView"
  pod 'CircleProgressBar', '~> 0.31’

end

target 'KooKooTodayWidget' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    pod "SwiftLocation"
    pod "Alamofire"
    
end